### PR TITLE
Vertex normals creation

### PR DESCRIPTION
**Pull request by kylebarron**
For #17 

How to aggregate triangles per vertex?
I essentially need to do: For every vertex, what are the indices of
`indices` that touch that vertex. This is basically a double for loop, or
at least a single for loop that does
    for i in range(indices.max()):
        (indices == i).any(axis=1)

That's obviously slow, and I'm not sure how to broadcast, because I'd need
to broadcast arrays of two different sizes.

https://stackoverflow.com/q/53631460
https://stackoverflow.com/q/8251541

### CODE REVIEW

**Comment by kylebarron** [comment]
Should be able to do 

```py
normals = compute_vertex_normals(positions, indices)
encoded = oct_encode(normals)
encoded.flatten('C')
encoded.tobytes('C')
```

**Comment by malaretv** [comment]
Interested in trying this out. How could I go about testing this in the context of dem-tiler?

**Comment by kylebarron** [comment]
I think this PR should be merge-ready. I just haven't looked at it in a while. You can try checking out this branch and generating some tiles. You should be able to visualize some with quantized mesh viewer https://github.com/heremaps/quantized-mesh-viewer

**Comment by malaretv** [comment]
Nice, just tried it out. I think the only missing step is encoding them into the returned quantized-mesh tile, or at least I'm not seeing it in the returned object (attached image)
image

I'll try adding the remaining pieces today and see if i have any luck!

**Comment by malaretv** [comment]
https://github.com/malaretv/quantized-mesh-encoder/commit/64d0ee582ae3cda79586dfad2e157f746b312695

With the bit of added logic in the above commit it seems to be at least encoding the vertexnormals to the tile.

The only issue is the vertexnormals themselves are pointing the opposite direction they should! The fix may be obvious but I'm new to numpy, quantized-mesh, the concept of normals, etc... Will keep poking around

image

**Comment by kylebarron** [comment]
> pointing the opposite direction they should

You might want to check the winding order of your input data? How are you generating the mesh?

**Comment by malaretv** [comment]
Here's how I'm reading in data
```python
    tile_size = 64
    use_martini = True
    mesh_max_error = float(100)

    with COGReader("../data/Lunar_dem.tif", tms=tms) as cog:
        # cog.tile(tile_x, tile_y, tile_z, **kwargs)
        img = cog.tile(x, y, z, tilesize=tile_size + 1)
        tile = img.data[0].astype("float32")  # Select first band

        if use_martini:
            martini = Martini(tile_size + 1)
            mar_tile = martini.create_tile(tile)

            vertices, triangles = mar_tile.get_mesh(mesh_max_error)
            rescaled = martini_rescale_positions(
                vertices, tile, bounds=img.bounds, flip_y=True
            )
        else:
            tin = Delatin(tile, max_error=mesh_max_error)
            vertices, triangles = tin.vertices, tin.triangles.flatten()
            rescaled = delatin_rescale_positions(vertices, img.bounds, flip_y=False)
        buf = io.BytesIO()
        quantized_mesh_encoder.encode(
            buf,
            rescaled,
            triangles,
            generate_normals=True,
            ellipsoid={"a": 1737400.0, "b": 1737400.0},
        )
```

I tried playing around with winding order but results were similar. There might be a deeper issue with how I'm encoding the normals in the returned object

**Comment by malaretv** [comment]
The behavior seems much better now. Not sure what did it, probably something in my testing setup. I put up the fork of this PR with the remaining pieces as a separate pull request.

Thanks so much for your help and all your work on this toolchain for generating meshes!

**Pull request merged**
