### PR TITLE
Add pyx file to pypi

### PR DESCRIPTION
**Pull request by davidbrochart**
Hey @kylebarron, it's me again :smile:

### CODE REVIEW

**Comment by davidbrochart** [comment]
Thanks for merging! A PyPI release would be nice, but there's no hurry.

**Comment by kylebarron** [comment]
Ok, I pushed a new release, and CI should be building the wheels now

**Comment by davidbrochart** [comment]
Awesome!

**Comment by kylebarron** [comment]
0.3.1 is on pypi now: https://pypi.org/project/quantized-mesh-encoder/0.3.1/

**Pull request merged**
